octopus:
  environments:
    - development
    - test
    # - production
  development:
    client_3:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: vuln_data_stinger_3_development
      host: localhost
      username: stinger
      password: quahgoh3veed4dieGhaewohXiachooxi
      pool: 5
      socket: /tmp/mysql.sock
  test:
    client_3:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: vuln_data_stinger_3_test
      host: localhost
      username: stinger
      password: quahgoh3veed4dieGhaewohXiachooxi
      pool: 5
      socket: /tmp/mysql.sock
