base-connection: &con
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  socket: /tmp/mysql.sock

octopus:
  environments:
    - development
    - test
    # - production
  development:
    client_2:
      <<: *con
      database: vuln_data_stinger_2_development
      username: stinger
      password: quahgoh3veed4dieGhaewohXiachooxi
  test:
    client_3:
      <<: *con
      database: vuln_data_stinger_3_test
      username: stinger
      password: quahgoh3veed4dieGhaewohXiachooxi
