octopus:
  environments:
    - development
    - test
    # - production
  development:
    client_3:
      host: localhost
      adapter: mysql2
      database: vuln_data_stinger_3_development
  test:
    shard_one:
      host: localhost
      adapter: mysql2
      database: vuln_data_stinger_3_test
